import { Metadata } from "next";  // Import metadata correctly
import localFont from "next/font/local";
import "./globals.css";
import DefaultProvider from "@/providers/redux-provider";

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata directly in layout file
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// No "use client" here
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DefaultProvider>
          {children}
        </DefaultProvider>
      </body>
    </html>
  );
}
